import assert from 'node:assert/strict';
import test from 'node:test';
import { createAdminCustomerRequestItemHandler, createAdminCustomerRequestsHandler, createCustomerRequestsGateway, createPublicCustomerRequestHandler } from '../server/customer-request-handler.js';
import { createSession, sessionCookie } from '../server/auth.js';

process.env.SESSION_SECRET = 'test-only-session-secret-with-more-than-32-characters';
const originHeaders = { origin: 'http://localhost', host: 'localhost', 'x-forwarded-proto': 'http' };
const valid = { fullName: 'Alex Citizen', email: 'Alex@example.com', subject: 'Integration support', details: 'Please help connect our workflow.', website: '' };
function response(){return{statusCode:200,headers:{},setHeader(name,value){this.headers[name]=value;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}};}
async function call(handler,method,{body,id,query={},authenticated=false,cookie,headers={}}={}){const res=response();const requestHeaders={...originHeaders,...headers};if(body!==undefined&&!requestHeaders['content-type'])requestHeaders['content-type']='application/json';if(authenticated)requestHeaders.cookie=sessionCookie(createSession('admin')).split(';')[0];if(cookie)requestHeaders.cookie=cookie;await handler({method,headers:requestHeaders,body,query:id===undefined?query:{...query,id},socket:{}},res);return res;}

test('valid public submission is stored with New status and can link a member session',async()=>{let saved;const repository={findUserIdBySession:async()=> '7',createCustomerRequest:async data=>{saved=data;return{id:'12',status:'New',createdAt:'2026-01-01'};}};const res=await call(createPublicCustomerRequestHandler(repository,()=>false),'POST',{body:valid,cookie:'terigent_user_session=member-token'});assert.equal(res.statusCode,201);assert.equal(saved.userId,'7');assert.equal(saved.email,'alex@example.com');assert.equal(res.payload.request.status,'New');assert.deepEqual(Object.keys(res.payload.request),['id','status','createdAt']);});
test('anonymous submissions remain unlinked',async()=>{let saved;const repository={findUserIdBySession:async()=>assert.fail(),createCustomerRequest:async data=>{saved=data;return{id:'1',status:'New'};}};assert.equal((await call(createPublicCustomerRequestHandler(repository,()=>false),'POST',{body:valid})).statusCode,201);assert.equal(saved.userId,null);});
test('invalid public input, extra fields, honeypot, and rate limit are handled',async()=>{const repository={createCustomerRequest:async()=>assert.fail()};let res=await call(createPublicCustomerRequestHandler(repository,()=>false),'POST',{body:{...valid,email:'bad'}});assert.equal(res.statusCode,400);assert.ok(res.payload.errors.email);res=await call(createPublicCustomerRequestHandler(repository,()=>false),'POST',{body:{...valid,adminNote:'no'}});assert.equal(res.statusCode,400);assert.ok(res.payload.errors.body);res=await call(createPublicCustomerRequestHandler(repository,()=>false),'POST',{body:{...valid,website:'bot'}});assert.equal(res.statusCode,201);res=await call(createPublicCustomerRequestHandler(repository,()=>true),'POST',{body:valid});assert.equal(res.statusCode,429);});
test('unauthorized users cannot list, read, or update requests',async()=>{const repository={listCustomerRequests:async()=>assert.fail(),getCustomerRequest:async()=>assert.fail(),updateCustomerRequestStatus:async()=>assert.fail()};assert.equal((await call(createAdminCustomerRequestsHandler(repository),'GET')).statusCode,401);assert.equal((await call(createAdminCustomerRequestItemHandler(repository),'GET',{id:'1',cookie:'terigent_user_session=member'})).statusCode,401);assert.equal((await call(createAdminCustomerRequestItemHandler(repository),'PATCH',{id:'1',body:{status:'Closed'}})).statusCode,401);});
test('administrator can filter, view details, and update status',async()=>{const item={id:'1',...valid,status:'New'};const repository={listCustomerRequests:async options=>({requests:[item],total:1,options}),getCustomerRequest:async()=>item,updateCustomerRequestStatus:async(id,status)=>({...item,id,status})};let res=await call(createAdminCustomerRequestsHandler(repository),'GET',{authenticated:true,query:{status:'New',page:'1',limit:'20'}});assert.equal(res.statusCode,200);assert.equal(res.payload.total,1);res=await call(createAdminCustomerRequestItemHandler(repository),'GET',{authenticated:true,id:'1'});assert.equal(res.payload.request.details,item.details);res=await call(createAdminCustomerRequestItemHandler(repository),'PATCH',{authenticated:true,id:'1',body:{status:'In Progress'}});assert.equal(res.statusCode,200);assert.equal(res.payload.request.status,'In Progress');});
test('invalid status, extra update fields, bad filter, and cross-origin mutation are rejected',async()=>{const repository={updateCustomerRequestStatus:async()=>assert.fail()};let res=await call(createAdminCustomerRequestItemHandler(repository),'PATCH',{authenticated:true,id:'1',body:{status:'Waiting'}});assert.equal(res.statusCode,400);assert.ok(res.payload.errors.status);res=await call(createAdminCustomerRequestItemHandler(repository),'PATCH',{authenticated:true,id:'1',body:{status:'Closed',details:'changed'}});assert.equal(res.statusCode,400);assert.ok(res.payload.errors.body);res=await call(createAdminCustomerRequestsHandler(repository),'GET',{authenticated:true,query:{status:'Waiting'}});assert.equal(res.statusCode,400);res=await call(createAdminCustomerRequestItemHandler(repository),'PATCH',{authenticated:true,id:'1',body:{status:'Closed'},headers:{origin:'https://evil.invalid'}});assert.equal(res.statusCode,403);});

test('combined function dispatches unchanged public and rewritten admin routes',async()=>{const item={id:'1',...valid,status:'New'};let created=false;const repository={findUserIdBySession:async()=>null,createCustomerRequest:async()=>{created=true;return{id:'2',status:'New'};},listCustomerRequests:async()=>({requests:[item],total:1}),getCustomerRequest:async()=>item,updateCustomerRequestStatus:async(id,status)=>({...item,id,status})};const gateway=createCustomerRequestsGateway(repository,()=>false);let res=await call(gateway,'POST',{body:valid});assert.equal(res.statusCode,201);assert.equal(created,true);res=await call(gateway,'GET',{authenticated:true,query:{requestRoute:'admin-list'}});assert.equal(res.statusCode,200);assert.equal(res.payload.total,1);res=await call(gateway,'GET',{authenticated:true,id:'1',query:{requestRoute:'admin-item'}});assert.equal(res.statusCode,200);assert.equal(res.payload.request.details,item.details);res=await call(gateway,'PATCH',{authenticated:true,id:'1',query:{requestRoute:'admin-item'},body:{status:'Resolved'}});assert.equal(res.statusCode,200);assert.equal(res.payload.request.status,'Resolved');assert.equal((await call(gateway,'GET',{query:{requestRoute:'admin-list'}})).statusCode,401);assert.equal((await call(gateway,'GET',{id:'1',query:{requestRoute:'admin-item'}})).statusCode,401);});
