import assert from 'node:assert/strict';
import test from 'node:test';
import { createDocumentsHandler } from '../server/document-handler.js';
import { hashSessionToken } from '../server/user-auth.js';
import { validateDocumentFile,MAX_FILE_BYTES } from '../server/document-validation.js';
const headers={origin:'http://localhost',host:'localhost','x-forwarded-proto':'http'};
const response=()=>({statusCode:200,headers:{},setHeader(name,value){this.headers[name]=value;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}});
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
const uploadFile={filename:'photo.png',mimeType:'image/png',buffer:png};
function setup(options={}){let sequence=0;const rows=[];const auth={findSession:async hash=>hash===hashSessionToken('alice')?{id:'1'}:hash===hashSessionToken('bob')?{id:'2'}:null};const repository={decodeCursor:()=>null,async listDocuments(userId){return{documents:rows.filter(row=>row.userId===userId),nextCursor:null};},async reserveUpload(userId,data,storageKey){if(options.limit)return{limitReached:true};const document={id:String(++sequence),userId,filename:data.filename,mimeType:data.mimeType,sizeBytes:data.sizeBytes,storageKey,status:'pending',createdAt:new Date().toISOString()};rows.push(document);return{document};},async markReady(userId,id){const row=rows.find(item=>item.id===id&&item.userId===userId);if(options.dbFailure)throw new Error('db down');if(row)row.status='ready';return row;},async removeReservation(userId,id){const index=rows.findIndex(item=>item.id===id&&item.userId===userId);if(index>=0)rows.splice(index,1);},async markCleanupNeeded(){},async findDocument(userId,id){return rows.find(item=>item.id===id&&item.userId===userId&&['ready','delete_failed'].includes(item.status))||null;},async finishDelete(userId,id){const index=rows.findIndex(item=>item.id===id&&item.userId===userId);if(index<0)return false;rows.splice(index,1);return true;},async markDeleteFailed(userId,id){const row=rows.find(item=>item.id===id&&item.userId===userId);if(row)row.status='delete_failed';}};const blobs={async uploadBlob(){if(options.blobFailure)throw new Error('blob down');},async deleteBlob(){if(options.deleteFailure)throw new Error('blob delete down');},async getBlob(){return null;}};const parser=async()=>({file:uploadFile});return{rows,handler:createDocumentsHandler(repository,auth,blobs,parser)};}
async function call(handler,method,{token,route='index',id,origin=headers.origin}={}){const res=response();await handler({method,headers:{...headers,origin,...(token?{cookie:`terigent_user_session=${token}`}:{})},query:{documentRoute:route,...(id?{id}:{})},socket:{}},res);return res;}
test('all document routes require a member session and set private no-store',async()=>{const api=setup();for(const [method,route] of [['GET','index'],['POST','index'],['GET','content'],['GET','download'],['DELETE','item']]){const res=await call(api.handler,method,{route,id:'1'});assert.equal(res.statusCode,401);assert.equal(res.payload.error,'Not authenticated.');assert.equal(res.headers['Cache-Control'],'private, no-store');}});
test('upload persists metadata with opaque storage key and isolates owners',async()=>{const api=setup();let res=await call(api.handler,'POST',{token:'alice'});assert.equal(res.statusCode,201);assert.match(api.rows[0].storageKey,/^documents\/[0-9a-f-]+\.png$/);assert.notEqual(api.rows[0].storageKey,uploadFile.filename);res=await call(api.handler,'GET',{token:'bob',route:'download',id:'1'});assert.equal(res.statusCode,404);res=await call(api.handler,'DELETE',{token:'bob',route:'item',id:'1'});assert.equal(res.statusCode,404);});
test('upload and delete enforce same-origin CSRF checks',async()=>{const api=setup();assert.equal((await call(api.handler,'POST',{token:'alice',origin:'https://evil.example'})).statusCode,403);await call(api.handler,'POST',{token:'alice'});assert.equal((await call(api.handler,'DELETE',{token:'alice',route:'item',id:'1',origin:'https://evil.example'})).statusCode,403);});
test('limits and storage failures never return false success',async()=>{assert.equal((await call(setup({limit:true}).handler,'POST',{token:'alice'})).payload.error,'Document limit reached.');for(const kind of ['blobFailure','dbFailure']){const api=setup({[kind]:true});const res=await call(api.handler,'POST',{token:'alice'});assert.equal(res.statusCode,500);assert.equal(res.payload.error,'Upload failed.');assert.equal(api.rows.length,0);}});
test('failed blob deletion remains retryable',async()=>{const api=setup({deleteFailure:true});await call(api.handler,'POST',{token:'alice'});const res=await call(api.handler,'DELETE',{token:'alice',route:'item',id:'1'});assert.equal(res.statusCode,500);assert.equal(res.payload.error,'Delete failed.');assert.equal(api.rows[0].status,'delete_failed');});
test('server validation rejects empty, oversized, unsupported, spoofed and corrupt files',async()=>{assert.equal((await validateDocumentFile({filename:'x.png',mimeType:'image/png',buffer:Buffer.alloc(0)})).error,'Empty file.');assert.equal((await validateDocumentFile({filename:'x.png',mimeType:'image/png',buffer:Buffer.alloc(MAX_FILE_BYTES+1)})).error,'File too large.');assert.equal((await validateDocumentFile({filename:'x.svg',mimeType:'image/svg+xml',buffer:png})).error,'Unsupported file type.');assert.equal((await validateDocumentFile({filename:'x.pdf',mimeType:'application/pdf',buffer:png})).error,'Invalid or corrupted file.');assert.equal((await validateDocumentFile({filename:'x.png',mimeType:'image/png',buffer:Buffer.from('not png')})).error,'Invalid or corrupted file.');assert.ok((await validateDocumentFile(uploadFile)).data);});
