import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { createClientItemHandler, createClientsHandler, createProjectItemHandler, createProjectsHandler, createStaffHandler } from '../server/project-handler.js';
import { normalizedProgress, validateClient, validateProject, validateStaffProgress } from '../server/project-validation.js';
import { createSession, sessionCookie } from '../server/auth.js';

process.env.SESSION_SECRET='project-test-session-secret-longer-than-32-characters';
const headers={origin:'http://localhost',host:'localhost','x-forwarded-proto':'http','content-type':'application/json'};
const rootCookie=sessionCookie(createSession('root')).split(';')[0];
const response=()=>({statusCode:200,headers:{},setHeader(name,value){this.headers[name]=value;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}});
async function call(handler,method,{body,query={},auth=true}={}){const res=response();await handler({method,body,query,headers:{...headers,...(auth?{cookie:rootCookie}:{})},socket:{}},res);return res;}
const client={name:'Voltix Labs',email:'team@voltix.test',phone:'+61 400 000 000'};
const project={name:'Client portal',description:'Delivery workspace',status:'in-progress',progress:35,clientId:'4',memberIds:['7','8']};

test('project management APIs require authentication',async()=>{const repository={listClients:async()=>assert.fail(),listProjects:async()=>assert.fail()};assert.equal((await call(createClientsHandler(repository),'GET',{auth:false})).statusCode,401);assert.equal((await call(createProjectsHandler(repository),'GET',{auth:false})).statusCode,401);});

test('root can complete client CRUD and protected client deletion reports conflict',async()=>{const repository={listClients:async()=>({clients:[],total:0}),createClient:async data=>({id:'1',...data}),updateClient:async(id,data)=>({id,...data}),deleteClient:async id=>id==='2'?{conflict:true}:{id}};let res=await call(createClientsHandler(repository),'POST',{body:client});assert.equal(res.statusCode,201);assert.equal(res.payload.client.email,client.email);res=await call(createClientItemHandler(repository),'PATCH',{body:{...client,name:'Voltix Group'},query:{id:'1'}});assert.equal(res.statusCode,200);assert.equal(res.payload.client.name,'Voltix Group');assert.equal((await call(createClientItemHandler(repository),'DELETE',{query:{id:'2'}})).statusCode,409);assert.equal((await call(createClientItemHandler(repository),'DELETE',{query:{id:'1'}})).statusCode,200);});

test('root can list assignees and complete project CRUD with members',async()=>{const item={id:'9',...project,clientName:'Voltix Labs',members:[]};const repository={listStaff:async()=>[{id:'7',name:'Sam'}],listProjects:async options=>({projects:[item],total:1,options}),createProject:async data=>({project:{...item,...data}}),getProject:async()=>item,updateProject:async(id,data)=>({project:{...item,...data,id}}),deleteProject:async id=>({id})};assert.equal((await call(createStaffHandler(repository),'GET')).payload.staff.length,1);assert.equal((await call(createProjectsHandler(repository),'GET')).statusCode,200);assert.equal((await call(createProjectsHandler(repository),'POST',{body:project})).statusCode,201);assert.equal((await call(createProjectItemHandler(repository),'GET',{query:{id:'9'}})).statusCode,200);assert.equal((await call(createProjectItemHandler(repository),'PATCH',{query:{id:'9'},body:{...project,progress:80}})).payload.project.progress,80);assert.equal((await call(createProjectItemHandler(repository),'DELETE',{query:{id:'9'}})).statusCode,200);});

test('invalid client, status, progress, client ID and member IDs are rejected',()=>{assert.equal(validateClient({...client,email:'bad'}).valid,false);assert.equal(validateProject({...project,status:'waiting'}).valid,false);assert.equal(validateProject({...project,progress:101}).valid,false);assert.equal(validateProject({...project,clientId:'bad'}).valid,false);assert.equal(validateProject({...project,memberIds:['7','7']}).valid,false);assert.equal(validateProject({...project,memberIds:['7','bad']}).valid,false);});

test('staff update validator permits only status and progress',()=>{assert.deepEqual(validateStaffProgress({status:'on-hold',progress:55}),{valid:true,data:{status:'on-hold',progress:55}});for(const body of [{name:'Changed'},{description:'Changed'},{clientId:'2'},{memberIds:['2']},{status:'bad'},{progress:-1},{progress:101}])assert.equal(validateStaffProgress(body).valid,false);});

test('status rules force or lock project progress',()=>{assert.equal(normalizedProgress('not-started',67,42),0);assert.equal(normalizedProgress('completed',67,42),100);assert.equal(normalizedProgress('on-hold',67,42),42);assert.equal(normalizedProgress('in-progress',67,42),67);assert.equal(validateProject({...project,status:'not-started',progress:67}).data.progress,0);assert.equal(validateProject({...project,status:'completed',progress:67}).data.progress,100);});

test('migration and repository enforce normalized relationships and assignment-scoped staff updates',async()=>{const migration=await readFile(new URL('../db/migrations/011_create_clients_and_projects.sql',import.meta.url),'utf8');assert.match(migration,/CREATE TABLE IF NOT EXISTS clients/);assert.match(migration,/CREATE TABLE IF NOT EXISTS projects/);assert.match(migration,/CREATE TABLE IF NOT EXISTS project_members/);assert.match(migration,/status IN \('not-started','in-progress','completed','on-hold'\)/);assert.match(migration,/progress BETWEEN 0 AND 100/);assert.match(migration,/client_id BIGINT NOT NULL REFERENCES clients\(id\) ON DELETE RESTRICT/);assert.match(migration,/user_id BIGINT NOT NULL REFERENCES users\(id\) ON DELETE RESTRICT/);assert.match(migration,/PRIMARY KEY \(project_id, user_id\)/);assert.doesNotMatch(migration,/DROP|TRUNCATE/i);const repository=await readFile(new URL('../server/project-repository.js',import.meta.url),'utf8');assert.match(repository,/pm\.project_id=p\.id AND pm\.user_id=\$2/);assert.match(repository,/role='staff'/);assert.match(repository,/DELETE FROM project_members WHERE project_id=\$1/);});

test('staff access policy is enforced in handler and repository layers',async()=>{const handler=await readFile(new URL('../server/project-handler.js',import.meta.url),'utf8');assert.match(handler,/user\.role==='staff'/);assert.match(handler,/validateStaffProgress\(payload\)/);assert.match(handler,/progress-locked/);assert.match(handler,/Only administrators can create projects/);assert.match(handler,/Only administrators can delete projects/);assert.match(handler,/This project is not assigned to you/);const repository=await readFile(new URL('../server/project-repository.js',import.meta.url),'utf8');assert.match(repository,/principal\.role==='staff'/);assert.match(repository,/project_members mine/);assert.match(repository,/updateStaffProgress\(id,userId,data\)/);assert.match(repository,/status!=='in-progress'/);assert.match(repository,/normalizedProgress\(status,requested,current\.progress\)/);});
