import assert from 'node:assert/strict';
import test from 'node:test';
import { createTasksHandler,createTaskItemHandler } from '../server/task-handler.js';
import { hashSessionToken } from '../server/user-auth.js';
const headers={origin:'http://localhost',host:'localhost','x-forwarded-proto':'http'};
const response=()=>({statusCode:200,headers:{},setHeader(name,value){this.headers[name]=value;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}});
const task={title:'Ship dashboard',description:'Protected work',status:'not-started',priority:'High',deadline:'2026-10-01',reminder:'No reminder',assignee:'',project:'Terigent'};
function setup(){let sequence=0;const rows=[];const auth={async findSession(hash){if(hash===hashSessionToken('alice'))return{id:'1',name:'Alice'};if(hash===hashSessionToken('bob'))return{id:'2',name:'Bob'};return null;}};const repository={async listTasks(userId){return rows.filter(row=>row.userId===userId);},async createTask(userId,data){const row={id:String(++sequence),userId,...data};rows.push(row);return row;},async updateTask(userId,id,data){const index=rows.findIndex(row=>row.id===id&&row.userId===userId);if(index<0)return null;rows[index]={...rows[index],...data};return rows[index];},async deleteTask(userId,id){const index=rows.findIndex(row=>row.id===id&&row.userId===userId);if(index<0)return null;return rows.splice(index,1)[0];}};return{rows,index:createTasksHandler(repository,auth),item:createTaskItemHandler(repository,auth)};}
async function call(handler,method,{token,body,id,origin=headers.origin}={}){const res=response();await handler({method,headers:{...headers,origin,...(token?{cookie:`terigent_user_session=${token}`}:{})},body,query:id?{id}:{},socket:{}},res);return res;}
test('task API requires a valid member session and never caches private data',async()=>{const api=setup();let res=await call(api.index,'GET');assert.equal(res.statusCode,401);assert.equal(res.headers['Cache-Control'],'private, no-store');res=await call(api.index,'GET',{token:'fake'});assert.equal(res.statusCode,401);});
test('members can persist and transition their own tasks while other members cannot access IDs',async()=>{const api=setup();let res=await call(api.index,'POST',{token:'alice',body:task});assert.equal(res.statusCode,201);const id=res.payload.task.id;res=await call(api.index,'GET',{token:'alice'});assert.equal(res.payload.tasks.length,1);res=await call(api.index,'GET',{token:'bob'});assert.equal(res.payload.tasks.length,0);res=await call(api.item,'PUT',{token:'bob',id,body:{...task,status:'completed'}});assert.equal(res.statusCode,404);res=await call(api.item,'PUT',{token:'alice',id,body:{...task,status:'in-progress'}});assert.equal(res.payload.task.status,'in-progress');res=await call(api.item,'PUT',{token:'alice',id,body:{...task,status:'completed'}});assert.equal(res.payload.task.status,'completed');res=await call(api.item,'PUT',{token:'alice',id,body:{...task,status:'not-started'}});assert.equal(res.payload.task.status,'not-started');res=await call(api.item,'DELETE',{token:'bob',id});assert.equal(res.statusCode,404);res=await call(api.item,'DELETE',{token:'alice',id});assert.equal(res.statusCode,200);assert.equal(api.rows.length,0);});
test('task mutations enforce origin, body whitelist and field validation',async()=>{const api=setup();let res=await call(api.index,'POST',{token:'alice',body:task,origin:'https://evil.example'});assert.equal(res.statusCode,403);res=await call(api.index,'POST',{token:'alice',body:{...task,userId:'2'}});assert.equal(res.statusCode,400);assert.ok(res.payload.errors.form);res=await call(api.index,'POST',{token:'alice',body:{...task,status:'admin'}});assert.equal(res.statusCode,400);});
