import assert from 'node:assert/strict';
import test from 'node:test';
import { createTaskAttachmentsHandler } from '../server/task-handler.js';
import { hashSessionToken } from '../server/user-auth.js';
const headers={origin:'http://localhost',host:'localhost','x-forwarded-proto':'http'};
const response=()=>({statusCode:200,headers:{},setHeader(name,value){this.headers[name]=value;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}});
function setup(){const tasks=[{id:'10',userId:'1'},{id:'20',userId:'2'}],documents=[{id:'1',userId:'1',status:'ready',filename:'photo.png',mimeType:'image/png'},{id:'2',userId:'1',status:'ready',filename:'brief.pdf',mimeType:'application/pdf'},{id:'3',userId:'2',status:'ready',filename:'private.pdf',mimeType:'application/pdf'},{id:'4',userId:'1',status:'delete_failed',filename:'broken.png',mimeType:'image/png'}],links=[];const auth={findSession:async hash=>hash===hashSessionToken('alice')?{id:'1'}:hash===hashSessionToken('bob')?{id:'2'}:null};const repository={async addAttachments(userId,taskId,ids){if(!tasks.some(task=>task.id===taskId&&task.userId===userId)||ids.some(id=>!documents.some(document=>document.id===id&&document.userId===userId&&document.status==='ready')))return null;for(const id of ids)if(!links.some(link=>link.taskId===taskId&&link.documentId===id))links.push({taskId,documentId:id});return links.filter(link=>link.taskId===taskId).map(link=>documents.find(document=>document.id===link.documentId));},async removeAttachment(userId,taskId,documentId){const index=links.findIndex(link=>link.taskId===taskId&&link.documentId===documentId&&tasks.some(task=>task.id===taskId&&task.userId===userId)&&documents.some(document=>document.id===documentId&&document.userId===userId));return index<0?null:links.splice(index,1)[0];}};return{handler:createTaskAttachmentsHandler(repository,auth),links};}
async function call(handler,method,{token='alice',id='10',documentId,body={documentIds:['1']},origin=headers.origin}={}){const res=response();await handler({method,headers:{...headers,origin,...(token?{cookie:`terigent_user_session=${token}`}:{})},query:{id,...(documentId?{documentId}:{})},body,socket:{}},res);return res;}
test('task attachments require authentication and CSRF',async()=>{const api=setup();assert.equal((await call(api.handler,'POST',{token:null})).statusCode,401);assert.equal((await call(api.handler,'POST',{origin:'https://evil.example'})).statusCode,403);assert.equal((await call(api.handler,'DELETE',{documentId:'1',origin:'https://evil.example'})).statusCode,403);});
test('owner can attach multiple ready documents without duplicate links',async()=>{const api=setup();let res=await call(api.handler,'POST',{body:{documentIds:['1','2']}});assert.equal(res.statusCode,200);assert.equal(res.payload.attachments.length,2);res=await call(api.handler,'POST',{body:{documentIds:['1']}});assert.equal(res.statusCode,200);assert.equal(api.links.length,2);});
test('cross-owner, unavailable, and missing task or documents share 404',async()=>{for(const options of [{body:{documentIds:['3']}},{body:{documentIds:['4']}},{id:'20',body:{documentIds:['1']}},{id:'999',body:{documentIds:['1']}}])assert.equal((await call(setup().handler,'POST',options)).statusCode,404);});
test('removing an attachment leaves the document and other task links intact',async()=>{const api=setup();await call(api.handler,'POST');api.links.push({taskId:'11',documentId:'1'});const res=await call(api.handler,'DELETE',{documentId:'1'});assert.equal(res.statusCode,200);assert.deepEqual(api.links,[{taskId:'11',documentId:'1'}]);});
test('attachment payload validation rejects empty, duplicate and invalid IDs',async()=>{const api=setup();for(const body of [{documentIds:[]},{documentIds:['1','1']},{documentIds:['bad']},{documentIds:['1'],userId:'2'}])assert.equal((await call(api.handler,'POST',{body})).statusCode,400);});
