import assert from 'node:assert/strict';
import test from 'node:test';
import { createUserAuthHandlers } from '../server/user-auth-handler.js';
import { hashSessionToken } from '../server/user-auth.js';

const headers={origin:'http://localhost',host:'localhost','x-forwarded-proto':'http'};
const response=()=>({statusCode:200,headers:{},setHeader(name,value){this.headers[name]=value;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}});
function memoryRepository(){let sequence=0;const users=[];const sessions=new Map();const attempts=[];return {users,sessions,attempts,async rateLimited(key,action,limit){return attempts.filter(x=>x.key===key&&x.action===action).length>=limit;},async recordAttempt(key,action){attempts.push({key,action});},async clearAttempts(key,action){for(let i=attempts.length-1;i>=0;i--)if(attempts[i].key===key&&attempts[i].action===action)attempts.splice(i,1);},async createUser(data){if(users.some(u=>u.email===data.email)){const e=new Error('unique');e.code='23505';throw e;}const user={id:String(++sequence),name:data.name,email:data.email,passwordHash:data.passwordHash,createdAt:new Date().toISOString()};users.push(user);const safe={...user};delete safe.passwordHash;return safe;},async findUserForLogin(email){return users.find(u=>u.email===email)||null;},async createSession(value){sessions.set(value.tokenHash,value);},async findSession(hash){const session=sessions.get(hash);if(!session||session.expiresAt<=new Date())return null;const safe={...users.find(u=>u.id===session.userId)};delete safe.passwordHash;return safe;},async revokeSession(hash){sessions.delete(hash);}};}
async function call(handler,method,body={},extraHeaders=headers){const res=response();await handler({method,headers:extraHeaders,body,socket:{remoteAddress:'127.0.0.1'}},res);return res;}

test('registration, normalized uniqueness, login, me and revoked logout session',async()=>{const repo=memoryRepository();const api=createUserAuthHandlers(repo);let res=await call(api.register,'POST',{name:'  Ada  ',email:'Ada@Example.COM ',password:'correct horse battery staple',confirmPassword:'correct horse battery staple'});assert.equal(res.statusCode,201);assert.equal(repo.users[0].email,'ada@example.com');assert.notEqual(repo.users[0].passwordHash,'correct horse battery staple');assert.equal(res.payload.user.passwordHash,undefined);res=await call(api.register,'POST',{name:'Other',email:'ADA@example.com',password:'correct horse battery staple',confirmPassword:'correct horse battery staple'});assert.equal(res.statusCode,409);res=await call(api.login,'POST',{email:'ADA@example.com',password:'correct horse battery staple'});assert.equal(res.statusCode,200);assert.equal(res.payload.user.passwordHash,undefined);const cookie=res.headers['Set-Cookie'].split(';')[0];assert.match(res.headers['Set-Cookie'],/HttpOnly/);assert.equal(res.headers['Set-Cookie'].includes([...repo.sessions.keys()][0]),false);res=await call(api.me,'GET',{}, {cookie});assert.equal(res.statusCode,200);assert.equal(res.payload.user.email,'ada@example.com');res=await call(api.logout,'POST',{}, {...headers,cookie});assert.equal(res.statusCode,200);res=await call(api.me,'GET',{}, {cookie});assert.equal(res.statusCode,401);});

test('invalid fields, mismatch, wrong password, fake and expired sessions are rejected',async()=>{const repo=memoryRepository();const api=createUserAuthHandlers(repo);let res=await call(api.register,'POST',{name:'',email:'bad',password:'short',confirmPassword:'different',role:'admin'});assert.equal(res.statusCode,400);assert.ok(res.payload.errors.form);await call(api.register,'POST',{name:'Ada',email:'ada@example.com',password:'correct horse battery staple',confirmPassword:'correct horse battery staple'});res=await call(api.login,'POST',{email:'ada@example.com',password:'wrong password value'});assert.equal(res.statusCode,401);assert.equal(res.payload.error,'Email or password is incorrect.');res=await call(api.me,'GET',{}, {cookie:'terigent_user_session=fake'});assert.equal(res.statusCode,401);repo.sessions.set(hashSessionToken('expired'),{userId:'1',expiresAt:new Date(0)});res=await call(api.me,'GET',{}, {cookie:'terigent_user_session=expired'});assert.equal(res.statusCode,401);});

test('origin protection, body limit, and database rate limiting apply',async()=>{const repo=memoryRepository();const api=createUserAuthHandlers(repo);let res=await call(api.register,'POST',{name:'Ada',email:'ada@example.com',password:'correct horse battery staple',confirmPassword:'correct horse battery staple'},{origin:'https://evil.example',host:'localhost','x-forwarded-proto':'http'});assert.equal(res.statusCode,403);res=await call(api.register,'POST',{name:'Ada',email:'ada@example.com',password:'x'.repeat(7000),confirmPassword:'x'.repeat(7000)});assert.equal(res.statusCode,413);for(let i=0;i<5;i++)await call(api.login,'POST',{email:'none@example.com',password:'a valid but incorrect password'});res=await call(api.login,'POST',{email:'none@example.com',password:'a valid but incorrect password'});assert.equal(res.statusCode,429);});
