import { hasValidOrigin } from './auth.js';
import { parseBody, send } from './http.js';
import { getAuthenticatedPrincipal } from './rbac.js';
import { PROJECT_STATUSES, validProjectId, validateClient, validateProject, validateStaffProgress } from './project-validation.js';
import { logServerError } from './logger.js';

const json=req=>String(req.headers?.['content-type']||'').toLowerCase().split(';')[0].trim()==='application/json';
const failure=(...args)=>{const [req,res,error,message]=args.length===4?args:[null,...args];logServerError('projects.manage',error,req);return send(res,500,{error:message});};
async function principal(req,res,roles,authenticate=getAuthenticatedPrincipal){let value;try{value=await authenticate(req);}catch(error){return failure(req,res,error,'Authorization is temporarily unavailable.');}if(!value){send(res,401,{error:'Sign-in is required.'});return null;}if(!roles.includes(value.role)){send(res,403,{error:'You do not have permission to perform this action.'});return null;}return value;}
function query(req){const page=Number(req.query?.page||1),limit=Number(req.query?.limit||50);const search=Array.isArray(req.query?.q)?null:(req.query?.q||'').trim();const status=Array.isArray(req.query?.status)?null:(req.query?.status||'');if(!Number.isInteger(page)||page<1||!Number.isInteger(limit)||limit<1||limit>100||typeof search!=='string'||search.length>100||(status&&!PROJECT_STATUSES.includes(status)))return null;return{page,limit,search,status,offset:(page-1)*limit};}
function body(req,res,max=10000){if(!hasValidOrigin(req)){send(res,403,{error:'Request origin could not be verified.'});return null;}if(!json(req)){send(res,415,{error:'Content-Type must be application/json.'});return null;}const parsed=parseBody(req,max);if(parsed.error){send(res,parsed.error==='too_large'?413:400,{error:'Invalid request body.'});return null;}return parsed.body;}

export function createClientsHandler(repository){return async(req,res)=>{const user=await principal(req,res,['root']);if(!user)return;if(!['GET','POST'].includes(req.method)){res.setHeader('Allow','GET, POST');return send(res,405,{error:'Method not allowed.'});}res.setHeader('Cache-Control','private, no-store');try{if(req.method==='GET'){const options=query(req);if(!options)return send(res,400,{error:'Invalid query parameters.'});const result=await repository.listClients(options);return send(res,200,{...result,page:options.page,limit:options.limit});}const payload=body(req,res);if(!payload)return;const checked=validateClient(payload);if(!checked.valid)return send(res,400,{error:'Please correct the highlighted fields.',errors:checked.errors});return send(res,201,{client:await repository.createClient(checked.data)});}catch(error){return failure(req,res,error,'Clients could not be processed right now.');}};}
export function createClientItemHandler(repository){return async(req,res)=>{const user=await principal(req,res,['root']);if(!user)return;if(!['PATCH','DELETE'].includes(req.method)){res.setHeader('Allow','PATCH, DELETE');return send(res,405,{error:'Method not allowed.'});}const id=req.query?.id;if(!validProjectId(id))return send(res,400,{error:'Invalid client ID.'});if(!hasValidOrigin(req))return send(res,403,{error:'Request origin could not be verified.'});try{if(req.method==='DELETE'){const deleted=await repository.deleteClient(id);if(deleted?.conflict)return send(res,409,{error:'This client still has projects and cannot be deleted.'});return deleted?send(res,200,{message:'Client deleted.'}):send(res,404,{error:'Client not found.'});}const payload=body(req,res);if(!payload)return;const checked=validateClient(payload);if(!checked.valid)return send(res,400,{error:'Please correct the highlighted fields.',errors:checked.errors});const client=await repository.updateClient(id,checked.data);return client?send(res,200,{client}):send(res,404,{error:'Client not found.'});}catch(error){return failure(res,error,'The client could not be changed right now.');}};}
export function createStaffHandler(repository){return async(req,res)=>{if(!await principal(req,res,['root']))return;if(req.method!=='GET'){res.setHeader('Allow','GET');return send(res,405,{error:'Method not allowed.'});}res.setHeader('Cache-Control','private, no-store');try{return send(res,200,{staff:await repository.listStaff()});}catch(error){return failure(res,error,'Team members could not be loaded right now.');}};}
export function createProjectsHandler(repository){return async(req,res)=>{const user=await principal(req,res,['root','staff']);if(!user)return;if(!['GET','POST'].includes(req.method)){res.setHeader('Allow','GET, POST');return send(res,405,{error:'Method not allowed.'});}if(req.method==='POST'&&user.role!=='root')return send(res,403,{error:'Only administrators can create projects.'});res.setHeader('Cache-Control','private, no-store');try{if(req.method==='GET'){const options=query(req);if(!options)return send(res,400,{error:'Invalid query parameters.'});const result=await repository.listProjects({...options,principal:user});return send(res,200,{...result,page:options.page,limit:options.limit,role:user.role});}const payload=body(req,res);if(!payload)return;const checked=validateProject(payload);if(!checked.valid)return send(res,400,{error:'Please correct the highlighted fields.',errors:checked.errors});const result=await repository.createProject(checked.data,user);if(result.invalid)return send(res,400,{error:result.invalid==='client'?'Client not found.':'Every assigned member must currently have the staff role.'});return send(res,201,result);}catch(error){return failure(res,error,'Projects could not be processed right now.');}};}
export function createProjectItemHandler(repository){return async(req,res)=>{const user=await principal(req,res,['root','staff']);if(!user)return;if(!['GET','PATCH','DELETE'].includes(req.method)){res.setHeader('Allow','GET, PATCH, DELETE');return send(res,405,{error:'Method not allowed.'});}const id=req.query?.id;if(!validProjectId(id))return send(res,400,{error:'Invalid project ID.'});if(req.method==='DELETE'&&user.role!=='root')return send(res,403,{error:'Only administrators can delete projects.'});res.setHeader('Cache-Control','private, no-store');try{if(req.method==='GET'){const project=await repository.getProject(id,user);if(project)return send(res,200,{project,role:user.role});if(user.role==='staff'&&await repository.projectExists(id))return send(res,403,{error:'This project is not assigned to you.'});return send(res,404,{error:'Project not found.'});}if(!hasValidOrigin(req))return send(res,403,{error:'Request origin could not be verified.'});if(req.method==='DELETE'){const deleted=await repository.deleteProject(id);return deleted?send(res,200,{message:'Project deleted.'}):send(res,404,{error:'Project not found.'});}const payload=body(req,res);if(!payload)return;if(user.role==='staff'){const checked=validateStaffProgress(payload);if(!checked.valid)return send(res,checked.errors.body?403:400,{error:checked.errors.body?'Team members may only update status and progress.':'Please correct the highlighted fields.',errors:checked.errors});const changed=await repository.updateStaffProgress(id,user.id,checked.data);if(changed?.reason==='progress-locked')return send(res,400,{error:'Progress can only be changed while a project is In Progress.',errors:{progress:'Change the status to In Progress before editing progress.'}});if(changed)return send(res,200,{project:await repository.getProject(id,user)});if(await repository.projectExists(id))return send(res,403,{error:'This project is not assigned to you.'});return send(res,404,{error:'Project not found.'});}const checked=validateProject(payload);if(!checked.valid)return send(res,400,{error:'Please correct the highlighted fields.',errors:checked.errors});const result=await repository.updateProject(id,checked.data,user);if(result.missing)return send(res,404,{error:'Project not found.'});if(result.invalid)return send(res,400,{error:result.invalid==='client'?'Client not found.':'Every assigned member must currently have the staff role.'});return send(res,200,result);}catch(error){return failure(res,error,'The project could not be changed right now.');}};}

export function createProjectGateway(repository){const routes={clients:createClientsHandler(repository),'client-item':createClientItemHandler(repository),staff:createStaffHandler(repository),projects:createProjectsHandler(repository),'project-item':createProjectItemHandler(repository)};return(req,res)=>routes[req.query?.managementRoute]?.(req,res)||send(res,404,{error:'Management route not found.'});}
