import { hasValidOrigin } from './auth.js';
import { parseBody,send } from './http.js';
import { hashSessionToken,readUserToken } from './user-auth.js';
import { validateTask } from './task-validation.js';
const validId=value=>/^[1-9]\d*$/.test(String(value||''));
async function member(req,authRepository){const token=readUserToken(req);return token?authRepository.findSession(hashSessionToken(token)):null;}
const taskFailure=(res,error,message)=>{const missing=error?.code==='42P01';console.error('Task operation failed:',missing?'user_tasks table is unavailable':error instanceof Error?error.message:'Unknown error');return send(res,500,{error:missing?'Tasks are not configured yet. Apply the pending database migration and try again.':message});};
const privateHeaders=res=>res.setHeader('Cache-Control','private, no-store');
export function createTasksHandler(repository,authRepository){return async(req,res)=>{privateHeaders(res);if(!['GET','POST'].includes(req.method)){res.setHeader('Allow','GET, POST');return send(res,405,{error:'Method not allowed.'});}try{const user=await member(req,authRepository);if(!user)return send(res,401,{error:'Sign-in is required.'});if(req.method==='GET')return send(res,200,{tasks:await repository.listTasks(user.id)});if(!hasValidOrigin(req))return send(res,403,{error:'Request origin could not be verified.'});const parsed=parseBody(req,8000);if(parsed.error)return send(res,parsed.error==='too_large'?413:400,{error:'Invalid request body.'});const result=validateTask(parsed.body);if(!result.valid)return send(res,400,{error:'Please correct the highlighted fields.',errors:result.errors});return send(res,201,{task:await repository.createTask(user.id,result.data)});}catch(error){return taskFailure(res,error,'Tasks are temporarily unavailable. Please try again.');}};}
export function createTaskItemHandler(repository,authRepository){return async(req,res)=>{privateHeaders(res);if(!['PUT','PATCH','DELETE'].includes(req.method)){res.setHeader('Allow','PUT, PATCH, DELETE');return send(res,405,{error:'Method not allowed.'});}try{const user=await member(req,authRepository);if(!user)return send(res,401,{error:'Sign-in is required.'});if(!hasValidOrigin(req))return send(res,403,{error:'Request origin could not be verified.'});const id=Array.isArray(req.query?.id)?req.query.id[0]:req.query?.id;if(!validId(id))return send(res,400,{error:'Invalid task ID.'});if(req.method==='DELETE'){const deleted=await repository.deleteTask(user.id,id);return deleted?send(res,200,{message:'Task deleted.'}):send(res,404,{error:'Task not found.'});}const parsed=parseBody(req,8000);if(parsed.error)return send(res,parsed.error==='too_large'?413:400,{error:'Invalid request body.'});const result=validateTask(parsed.body);if(!result.valid)return send(res,400,{error:'Please correct the highlighted fields.',errors:result.errors});const task=await repository.updateTask(user.id,id,result.data);return task?send(res,200,{task}):send(res,404,{error:'Task not found.'});}catch(error){return taskFailure(res,error,'The task could not be changed right now. Please try again.');}};}
