import { useEffect,useState } from 'react';
import { HiOutlineDocument,HiOutlineXMark } from 'react-icons/hi2';
import memberRequest from './memberRequest';

export default function AttachmentPicker({task,onClose,onSaved}){
 const [documents,setDocuments]=useState([]),[cursor,setCursor]=useState(null),[selected,setSelected]=useState(new Set()),[state,setState]=useState({loading:true,saving:false,error:''});const attached=new Set((task.attachments||[]).map(item=>item.id));
 const load=async(next=null)=>{setState(current=>({...current,loading:true,error:''}));try{const data=await memberRequest(`/api/documents${next?`?cursor=${encodeURIComponent(next)}`:''}`);setDocuments(current=>next?[...current,...(data.documents||[])]:data.documents||[]);setCursor(data.nextCursor||null);}catch(error){setState(current=>({...current,error:error.message}));}finally{setState(current=>({...current,loading:false}));}};
 useEffect(()=>{load();},[]);
 const toggle=id=>setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next;});
 const save=async()=>{if(!selected.size||state.saving)return;setState(current=>({...current,saving:true,error:''}));try{const data=await memberRequest(`/api/tasks/${task.id}/documents`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentIds:[...selected]})});onSaved(data.attachments);onClose();}catch(error){setState(current=>({...current,saving:false,error:error.message}));}};
 return <div className="attachment-picker-backdrop" role="dialog" aria-modal="true" aria-labelledby="attachment-picker-title" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div className="attachment-picker"><div className="modal-heading"><h3 id="attachment-picker-title">Attach documents</h3><button className="icon-button" type="button" onClick={onClose} aria-label="Close attachment picker"><HiOutlineXMark/></button></div>{state.error&&<p className="auth-notice error" role="alert">{state.error}</p>}{!state.loading&&!documents.length?<div className="documents-empty"><HiOutlineDocument/><strong>No documents available</strong><span>Upload a file in My Documents first.</span></div>:<div className="attachment-options">{documents.map(document=>{const disabled=attached.has(document.id)||document.status!=='ready';return <label className={disabled?'attached':''} key={document.id}><input type="checkbox" checked={attached.has(document.id)||selected.has(document.id)} disabled={disabled} onChange={()=>toggle(document.id)}/><span><strong>{document.filename}</strong><small>{document.mimeType==='application/pdf'?'PDF':'Image'}{attached.has(document.id)?' · Already attached':document.status!=='ready'?' · Unavailable':''}</small></span></label>;})}</div>}{state.loading&&<p role="status">Loading documents...</p>}{cursor&&<button className="button button-ghost button-small" type="button" disabled={state.loading} onClick={()=>load(cursor)}>Load more</button>}<div className="form-actions"><button className="button button-ghost" type="button" onClick={onClose}>Cancel</button><button className="button" type="button" disabled={!selected.size||state.saving} onClick={save}>{state.saving?'Attaching...':`Attach ${selected.size||''}`}</button></div></div></div>;
}
