import { useEffect,useRef,useState } from 'react';
import { HiOutlineArrowDownTray,HiOutlineDocument,HiOutlineTrash,HiOutlineXMark } from 'react-icons/hi2';
import memberRequest from './memberRequest';
const MAX_BYTES=3*1024*1024,allowed=new Set(['image/jpeg','image/png','image/webp','application/pdf']);
const size=value=>value<1024?`${value} B`:value<1048576?`${(value/1024).toFixed(1)} KiB`:`${(value/1048576).toFixed(2)} MiB`;
const typeLabel=value=>value==='application/pdf'?'PDF':value.split('/')[1].toUpperCase();
export default function DocumentManager(){
 const [documents,setDocuments]=useState([]),[nextCursor,setNextCursor]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(''),[file,setFile]=useState(null),[notice,setNotice]=useState({type:'',text:''}),[preview,setPreview]=useState(null);const input=useRef();
 const load=async(cursor=null)=>{try{const data=await memberRequest(`/api/documents${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`);setDocuments(current=>cursor?[...current,...(data.documents||[])]:data.documents||[]);setNextCursor(data.nextCursor||null);}catch(error){if(error.status===401)window.location.replace('/login?returnTo=%2Fdashboard');else setNotice({type:'error',text:error.message});}finally{setLoading(false);}};
 useEffect(()=>{let current=true;memberRequest('/api/documents').then(data=>{if(current){setDocuments(data.documents||[]);setNextCursor(data.nextCursor||null);}}).catch(error=>{if(!current)return;if(error.status===401)window.location.replace('/login?returnTo=%2Fdashboard');else setNotice({type:'error',text:error.message});}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[]);
 const choose=event=>{const selected=event.target.files?.[0]||null;setNotice({type:'',text:''});if(!selected)return setFile(null);let error='';if(!allowed.has(selected.type))error='Unsupported file type.';else if(!selected.size)error='Empty file.';else if(selected.size>MAX_BYTES)error='File too large.';if(error){setFile(null);event.target.value='';setNotice({type:'error',text:error});}else setFile(selected);};
 const upload=async event=>{event.preventDefault();if(!file||busy)return;setBusy(true);setNotice({type:'',text:''});const body=new FormData();body.append('file',file);try{const data=await memberRequest('/api/documents',{method:'POST',body});setDocuments(current=>[data.document,...current]);setFile(null);if(input.current)input.current.value='';setNotice({type:'success',text:'Document uploaded.'});}catch(error){setNotice({type:'error',text:error.message});}finally{setBusy(false);}};
 const remove=async document=>{if(deleting||!window.confirm(`Delete “${document.filename}”? This cannot be undone.`))return;setDeleting(document.id);setNotice({type:'',text:''});try{await memberRequest(`/api/documents/${document.id}`,{method:'DELETE'});setDocuments(current=>current.filter(item=>item.id!==document.id));setPreview(current=>current?.id===document.id?null:current);setNotice({type:'success',text:'Document deleted.'});}catch(error){setNotice({type:'error',text:error.message});}finally{setDeleting('');}};
 return <section className="documents-section" aria-labelledby="documents-title"><div className="documents-heading"><p className="eyebrow"><span/> PRIVATE FILES</p><h2 id="documents-title">My Documents</h2><p>Keep images and PDFs securely with your account. Up to 30 files, 3 MiB each.</p></div><form className="document-upload" onSubmit={upload}><label><span>Choose one JPG, PNG, WebP, or PDF</span><input ref={input} type="file" name="file" accept=".jpg,.jpeg,.png,.webp,.pdf,image/jpeg,image/png,image/webp,application/pdf" onChange={choose} disabled={busy}/></label>{file&&<div className="selected-file"><strong>{file.name}</strong><span>{size(file.size)}</span></div>}<button className="button" type="submit" disabled={!file||busy}>{busy?'Uploading...':'Upload'}</button></form>{notice.text&&<p className={`auth-notice ${notice.type}`} role={notice.type==='error'?'alert':'status'}>{notice.text}</p>}{loading?<p role="status">Loading your documents...</p>:!documents.length?<div className="documents-empty"><HiOutlineDocument/><strong>No documents yet</strong><span>Choose a file above to add your first document.</span></div>:<div className="document-list">{documents.map(document=><article className="document-card" key={document.id}>{document.mimeType.startsWith('image/')?<button className="document-thumb" type="button" onClick={()=>setPreview(document)} aria-label={`Preview ${document.filename}`}><img src={`/api/documents/${document.id}/content`} alt=""/></button>:<div className="document-icon"><HiOutlineDocument/></div>}<div className="document-details"><strong>{document.filename}</strong><span>{typeLabel(document.mimeType)} · {size(document.sizeBytes)} · {new Date(document.createdAt).toLocaleString()}</span>{document.status==='delete_failed'&&<small>Previous deletion failed. You can safely retry.</small>}</div><div className="document-actions"><a className="button button-ghost button-small" href={`/api/documents/${document.id}/download`}><HiOutlineArrowDownTray/> Download</a><button className="button button-ghost button-small document-delete" type="button" disabled={Boolean(deleting)} onClick={()=>remove(document)}><HiOutlineTrash/> {deleting===document.id?'Deleting...':'Delete'}</button></div></article>)}</div>}{nextCursor&&<button className="button button-ghost load-more" disabled={loading} onClick={()=>load(nextCursor)}>Load more</button>}{preview&&<div className="document-preview" role="dialog" aria-modal="true" aria-label={`Preview ${preview.filename}`} onClick={()=>setPreview(null)}><div onClick={event=>event.stopPropagation()}><button type="button" onClick={()=>setPreview(null)} aria-label="Close preview"><HiOutlineXMark/></button><img src={`/api/documents/${preview.id}/content`} alt={preview.filename}/><p>{preview.filename}</p></div></div>}</section>;
}
