import { useEffect,useRef,useState } from 'react';
import { HiOutlineArrowPath,HiOutlineXMark } from 'react-icons/hi2';

export default function ImagePreview({document:item,onClose,returnFocus}){
 const [state,setState]=useState({loading:true,error:'',url:''}),[retry,setRetry]=useState(0),closeRef=useRef(),closeCallback=useRef(onClose);
 useEffect(()=>{closeCallback.current=onClose;},[onClose]);
 useEffect(()=>{const controller=new AbortController();let objectUrl='';fetch(`/api/documents/${item.id}/content`,{credentials:'same-origin',cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===401?'Your session has expired.':'Preview could not be loaded.');const type=response.headers.get('content-type')||'';if(!type.startsWith('image/'))throw new Error('Preview could not be loaded.');return response.blob();}).then(blob=>{objectUrl=URL.createObjectURL(blob);setState({loading:false,error:'',url:objectUrl});}).catch(error=>{if(error.name!=='AbortError')setState({loading:false,error:error.message||'Preview could not be loaded.',url:''});});return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};},[item.id,retry]);
 useEffect(()=>{const previous=globalThis.document.activeElement,target=returnFocus?.current;const keydown=event=>{if(event.key==='Escape')closeCallback.current();};globalThis.document.addEventListener('keydown',keydown);closeRef.current?.focus();return()=>{globalThis.document.removeEventListener('keydown',keydown);(target||previous)?.focus?.();};},[returnFocus]);
 const retryLoad=()=>{setState({loading:true,error:'',url:''});setRetry(value=>value+1);};
 return <div className="document-preview" role="dialog" aria-modal="true" aria-labelledby="image-preview-title" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><div><button ref={closeRef} type="button" onClick={onClose} aria-label="Close preview"><HiOutlineXMark/></button><h2 id="image-preview-title">{item.filename}</h2>{state.loading&&<p role="status">Loading preview...</p>}{state.error&&<div className="preview-error" role="alert"><p>{state.error}</p><button className="button button-small" type="button" onClick={retryLoad}><HiOutlineArrowPath/> Retry</button></div>}{state.url&&<img src={state.url} alt={item.filename}/>}</div></div>;
}
