import { useCallback, useEffect, useState } from 'react';
import { HiOutlinePencilSquare, HiOutlinePlus, HiOutlineTrash } from 'react-icons/hi2';
import Logo from './Logo';
import { showNotification } from './notifications';

const STATUSES = [['not-started', 'Not Started'], ['in-progress', 'In Progress'], ['completed', 'Completed'], ['on-hold', 'On Hold']];
const emptyClient = { name: '', email: '', phone: '' };
const emptyProject = { name: '', description: '', status: 'not-started', progress: 0, clientId: '', memberIds: [] };
async function api(url, options) { const response = await fetch(url, options); const payload = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(payload.error || 'The request failed.'); error.status = response.status; throw error; } return payload; }
const request = (method, body) => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
const label = status => STATUSES.find(item => item[0] === status)?.[1] || status;
const statusProgress = (status, current) => status === 'not-started' ? 0 : status === 'completed' ? 100 : current;
const boundedProgress = value => Math.min(100, Math.max(0, Math.trunc(Number(value) || 0)));
const pageCount = meta => Math.max(1, Math.ceil(meta.total / meta.limit));
function Pager({ meta, onPage }) { if (meta.total <= meta.limit) return null; return <nav className="service-pagination" aria-label="Result pages"><button className="button button-ghost button-small" disabled={meta.page <= 1} onClick={() => onPage(meta.page - 1)}>Previous</button><span>Page {meta.page} of {pageCount(meta)}</span><button className="button button-ghost button-small" disabled={meta.page >= pageCount(meta)} onClick={() => onPage(meta.page + 1)}>Next</button></nav>; }

export default function ProjectManagement() {
  const [session, setSession] = useState({ loading: true, role: null, error: '' });
  const [projects, setProjects] = useState([]), [clients, setClients] = useState([]), [staff, setStaff] = useState([]);
  const [filter, setFilter] = useState({ q: '', status: '' }), [clientSearch, setClientSearch] = useState('');
  const [projectMeta, setProjectMeta] = useState({ page: 1, limit: 12, total: 0 }), [clientMeta, setClientMeta] = useState({ page: 1, limit: 10, total: 0 });
  const [selected, setSelected] = useState(null), [projectForm, setProjectForm] = useState(emptyProject), [clientForm, setClientForm] = useState(emptyClient);
  const [editingProject, setEditingProject] = useState(null), [editingClient, setEditingClient] = useState(null);
  const root = session.role === 'root';
  const load = useCallback(async (role, q = '', status = '', projectPage = 1, clientPage = 1, clientQuery = '') => {
    const projectCall = api(`/api/projects?page=${projectPage}&limit=12${q ? `&q=${encodeURIComponent(q)}` : ''}${status ? `&status=${encodeURIComponent(status)}` : ''}`);
    try {
      if (role === 'root') {
        const [p, c, s] = await Promise.all([projectCall, api(`/api/clients?page=${clientPage}&limit=10${clientQuery ? `&q=${encodeURIComponent(clientQuery)}` : ''}`), api('/api/projects/assignees')]);
        setProjects(p.projects || []); setProjectMeta({ page: p.page || projectPage, limit: p.limit || 12, total: p.total || 0 });
        setClients(c.clients || []); setClientMeta({ page: c.page || clientPage, limit: c.limit || 10, total: c.total || 0 }); setStaff(s.staff || []);
      } else {
        const p = await projectCall; setProjects(p.projects || []); setProjectMeta({ page: p.page || projectPage, limit: p.limit || 12, total: p.total || 0 });
      }
    } catch (error) { showNotification(error.message, { type: 'error' }); }
  }, []);
  useEffect(() => { api('/api/admin/auth/session').then(value => { if (!value.authenticated) throw Object.assign(new Error('Sign in to access projects.'), { status: 401 }); setSession({ loading: false, role: value.role, error: '' }); return load(value.role); }).catch(error => setSession({ loading: false, role: null, error: error.message, status: error.status })); }, [load]);
  useEffect(() => { const enforce = event => { const input = event.target; if (!(input instanceof HTMLInputElement) || input.type !== 'number' || input.max !== '100') return; input.value = String(boundedProgress(input.value)); }; document.addEventListener('input', enforce, true); return () => document.removeEventListener('input', enforce, true); }, []);
  const reload = () => load(session.role, filter.q, filter.status, projectMeta.page, clientMeta.page, clientSearch);
  const saveClient = async event => { event.preventDefault(); try { await api(editingClient ? `/api/clients/${editingClient}` : '/api/clients', request(editingClient ? 'PATCH' : 'POST', clientForm)); setClientForm(emptyClient); setEditingClient(null); await reload(); showNotification('Client saved.', { type: 'success' }); } catch (error) { showNotification(error.message, { type: 'error' }); } };
  const saveProject = async event => { event.preventDefault(); try { await api(editingProject ? `/api/projects/${editingProject}` : '/api/projects', request(editingProject ? 'PATCH' : 'POST', { ...projectForm, progress: boundedProgress(projectForm.progress) })); setProjectForm(emptyProject); setEditingProject(null); setSelected(null); await reload(); showNotification('Project saved.', { type: 'success' }); } catch (error) { showNotification(error.message, { type: 'error' }); } };
  const remove = async (kind, item) => { if (!window.confirm(`Delete “${item.name}”? This cannot be undone.`)) return; try { await api(`/api/${kind}/${item.id}`, { method: 'DELETE' }); if (selected?.id === item.id) setSelected(null); await reload(); showNotification(`${kind === 'clients' ? 'Client' : 'Project'} deleted.`, { type: 'success' }); } catch (error) { showNotification(error.message, { type: 'error' }); } };
  const updateProgress = async (project, changes) => { const safe = changes.progress === undefined ? changes : { ...changes, progress: boundedProgress(changes.progress) }; try { const payload = await api(`/api/projects/${project.id}`, request('PATCH', safe)); setProjects(current => current.map(item => item.id === project.id ? payload.project : item)); setSelected(current => current?.id === project.id ? payload.project : current); showNotification('Project progress updated.', { type: 'success' }); } catch (error) { await reload(); showNotification(error.message, { type: 'error' }); } };
  const editProject = item => { setEditingProject(item.id); setProjectForm({ name: item.name, description: item.description, status: item.status, progress: item.progress, clientId: item.clientId, memberIds: item.members.map(member => member.id) }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  if (session.loading) return <main className="project-shell"><p role="status">Checking project access...</p></main>;
  if (!session.role) return <main className="project-shell"><section className="project-access"><Logo /><h1>Project access unavailable</h1><p>{session.error}</p><a className="button" href={session.status === 401 ? '/login?returnTo=%2Fprojects' : '/dashboard'}>{session.status === 401 ? 'Sign in' : 'Return to dashboard'}</a></section></main>;
  return <main className="project-shell"><div className="project-page">
    <header className="project-header"><div><Logo href={root ? '/admin' : '/dashboard'} /><h1>{root ? 'Client & project management' : 'My assigned projects'}</h1><p>{root ? 'Manage clients, delivery and team assignments.' : 'Update progress for projects assigned to you.'}</p></div><a className="button button-ghost" href={root ? '/admin' : '/dashboard'}>Back</a></header>
    <section className="project-stats"><div><strong>{projectMeta.total}</strong><span>Matching projects</span></div><div><strong>{projects.filter(item => item.status === 'in-progress').length}</strong><span>Active on page</span></div><div><strong>{projects.filter(item => item.status === 'completed').length}</strong><span>Completed on page</span></div></section>
    {root && <div className="project-editors"><section className="admin-panel client-editor"><h2>{editingClient ? 'Edit client' : 'New client'}</h2><form className="project-form" onSubmit={saveClient}><label>Name<input required maxLength="120" value={clientForm.name} onChange={event => setClientForm({ ...clientForm, name: event.target.value })} /></label><label>Email<input required type="email" maxLength="254" value={clientForm.email} onChange={event => setClientForm({ ...clientForm, email: event.target.value })} /></label><label>Phone<input maxLength="40" value={clientForm.phone} onChange={event => setClientForm({ ...clientForm, phone: event.target.value })} /></label><div className="project-actions client-actions">{editingClient && <button type="button" className="button button-ghost" onClick={() => { setEditingClient(null); setClientForm(emptyClient); }}>Cancel</button>}<button className="button"><HiOutlinePlus /> Save client</button></div></form></section>
      <section className="admin-panel"><h2>{editingProject ? 'Edit project' : 'New project'}</h2><form className="project-form" onSubmit={saveProject}><label>Name<input required maxLength="120" value={projectForm.name} onChange={event => setProjectForm({ ...projectForm, name: event.target.value })} /></label><label>Client<select required value={projectForm.clientId} onChange={event => setProjectForm({ ...projectForm, clientId: event.target.value })}><option value="">Select client</option>{clients.map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Status<select value={projectForm.status} onChange={event => { const status = event.target.value; setProjectForm({ ...projectForm, status, progress: statusProgress(status, projectForm.progress) }); }}>{STATUSES.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" disabled={projectForm.status !== 'in-progress'} value={projectForm.progress} onChange={event => setProjectForm({ ...projectForm, progress: event.target.value })} /></label><label className="full">Description<textarea rows="4" maxLength="3000" value={projectForm.description} onChange={event => setProjectForm({ ...projectForm, description: event.target.value })} /></label><fieldset className="full member-picker"><legend>Team members</legend>{staff.length ? staff.map(member => <label key={member.id}><input type="checkbox" checked={projectForm.memberIds.includes(member.id)} onChange={event => setProjectForm({ ...projectForm, memberIds: event.target.checked ? [...projectForm.memberIds, member.id] : projectForm.memberIds.filter(id => id !== member.id) })} /><span>{member.name}<small>{member.email}</small></span></label>) : <p>No staff accounts are available.</p>}</fieldset><div className="project-actions full">{editingProject && <button type="button" className="button button-ghost" onClick={() => { setEditingProject(null); setProjectForm(emptyProject); }}>Cancel</button>}<button className="button"><HiOutlinePlus /> Save project</button></div></form></section></div>}
    {root && <section className="admin-panel"><div className="project-list-heading"><h2>Clients</h2><form onSubmit={event => { event.preventDefault(); load(session.role, filter.q, filter.status, projectMeta.page, 1, clientSearch); }}><input aria-label="Search clients" placeholder="Search client name or email" value={clientSearch} onChange={event => setClientSearch(event.target.value)} /><button className="button button-small">Search</button></form></div>{!clients.length && <p>No clients match this search.</p>}<div className="admin-list">{clients.map(client => <article key={client.id}><div><h3>{client.name}</h3><p>{client.email}{client.phone && ` · ${client.phone}`}</p><small>{client.projectCount} project(s)</small></div><div><button className="button button-ghost button-small" onClick={() => { setEditingClient(client.id); setClientForm({ name: client.name, email: client.email, phone: client.phone }); }}><HiOutlinePencilSquare /> Edit</button><button className="button button-danger button-small" onClick={() => remove('clients', client)}><HiOutlineTrash /> Delete</button></div></article>)}</div><Pager meta={clientMeta} onPage={page => load(session.role, filter.q, filter.status, projectMeta.page, page, clientSearch)} /></section>}
    <section className="admin-panel"><div className="project-list-heading"><h2>Projects</h2><form onSubmit={event => { event.preventDefault(); load(session.role, filter.q, filter.status, 1, clientMeta.page, clientSearch); }}><input aria-label="Search projects" placeholder="Search project or client" value={filter.q} onChange={event => setFilter({ ...filter, q: event.target.value })} /><select aria-label="Filter project status" value={filter.status} onChange={event => { const next = { ...filter, status: event.target.value }; setFilter(next); load(session.role, next.q, next.status, 1, clientMeta.page, clientSearch); }}><option value="">All statuses</option>{STATUSES.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select><button className="button button-small">Search</button></form></div>{!projects.length && <p>No projects are available.</p>}<div className="project-grid">{projects.map(project => <article className="project-card" key={project.id}><button className="project-card-main" onClick={() => setSelected(project)}><span className={`project-status status-${project.status}`}>{label(project.status)}</span><h3>{project.name}</h3><p>{project.clientName}</p><div className="progress-track"><span style={{ width: `${project.progress}%` }} /></div><small>{project.progress}% · {project.members.map(member => member.name).join(', ') || 'Unassigned'}</small></button>{root ? <div className="project-card-actions"><button onClick={() => editProject(project)}><HiOutlinePencilSquare /> Edit</button><button onClick={() => remove('projects', project)}><HiOutlineTrash /> Delete</button></div> : <div className="staff-progress"><label>Status<select value={project.status} onChange={event => updateProgress(project, { status: event.target.value })}>{STATUSES.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" disabled={project.status !== 'in-progress'} value={project.progress} onBlur={event => updateProgress(project, { progress: Number(event.target.value) })} onChange={event => setProjects(current => current.map(item => item.id === project.id ? { ...item, progress: Number(event.target.value) } : item))} /></label></div>}</article>)}</div><Pager meta={projectMeta} onPage={page => load(session.role, filter.q, filter.status, page, clientMeta.page, clientSearch)} /></section>
    {selected && <section className="admin-panel project-detail"><div><span className={`project-status status-${selected.status}`}>{label(selected.status)}</span><h2>{selected.name}</h2><p>{selected.description || 'No description provided.'}</p></div><dl><div><dt>Client</dt><dd>{selected.clientName}</dd></div><div><dt>Progress</dt><dd>{selected.progress}%</dd></div><div><dt>Team</dt><dd>{selected.members.map(member => member.name).join(', ') || 'Unassigned'}</dd></div><div><dt>Updated</dt><dd>{new Date(selected.updatedAt).toLocaleString()}</dd></div></dl></section>}
  </div></main>;
}
