import { useCallback, useEffect, useState } from 'react';
import { HiOutlinePencilSquare, HiOutlinePlus, HiOutlineTrash } from 'react-icons/hi2';
import Logo from './Logo';

const STATUSES=[['not-started','Not Started'],['in-progress','In Progress'],['completed','Completed'],['on-hold','On Hold']];
const emptyClient={name:'',email:'',phone:''};
const emptyProject={name:'',description:'',status:'not-started',progress:0,clientId:'',memberIds:[]};
async function api(url,options){const response=await fetch(url,options);const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error||'The request failed.');error.status=response.status;throw error;}return payload;}
const request=(method,body)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const label=status=>STATUSES.find(item=>item[0]===status)?.[1]||status;
const statusProgress=(status,current)=>status==='not-started'?0:status==='completed'?100:current;
const boundedProgress=value=>Math.min(100,Math.max(0,Math.trunc(Number(value)||0)));

export default function ProjectManagement(){
 const [session,setSession]=useState({loading:true,role:null,error:''});const [projects,setProjects]=useState([]);const [clients,setClients]=useState([]);const [staff,setStaff]=useState([]);const [filter,setFilter]=useState({q:'',status:''});const [selected,setSelected]=useState(null);const [projectForm,setProjectForm]=useState(emptyProject);const [clientForm,setClientForm]=useState(emptyClient);const [editingProject,setEditingProject]=useState(null);const [editingClient,setEditingClient]=useState(null);const root=session.role==='root';
 const load=useCallback(async(role,q='',status='')=>{const projectCall=api(`/api/projects?limit=100${q?`&q=${encodeURIComponent(q)}`:''}${status?`&status=${encodeURIComponent(status)}`:''}`);try{if(role==='root'){const [p,c,s]=await Promise.all([projectCall,api('/api/clients?limit=100'),api('/api/projects/assignees')]);setProjects(p.projects||[]);setClients(c.clients||[]);setStaff(s.staff||[]);}else{const p=await projectCall;setProjects(p.projects||[]);}}catch(error){window.alert(error.message);}},[]);
 useEffect(()=>{api('/api/admin/auth/session').then(value=>{if(!value.authenticated)throw Object.assign(new Error('Sign in to access projects.'),{status:401});setSession({loading:false,role:value.role,error:''});return load(value.role);}).catch(error=>setSession({loading:false,role:null,error:error.message,status:error.status}));},[load]);
 useEffect(()=>{const enforceProgressRange=event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=='number'||input.max!=='100')return;input.value=String(boundedProgress(input.value));};document.addEventListener('input',enforceProgressRange,true);return()=>document.removeEventListener('input',enforceProgressRange,true);},[]);
 const saveClient=async event=>{event.preventDefault();try{await api(editingClient?`/api/clients/${editingClient}`:'/api/clients',request(editingClient?'PATCH':'POST',clientForm));setClientForm(emptyClient);setEditingClient(null);await load(session.role,filter.q,filter.status);window.alert('Client saved.');}catch(error){window.alert(error.message);}};
 const saveProject=async event=>{event.preventDefault();try{await api(editingProject?`/api/projects/${editingProject}`:'/api/projects',request(editingProject?'PATCH':'POST',{...projectForm,progress:boundedProgress(projectForm.progress)}));setProjectForm(emptyProject);setEditingProject(null);setSelected(null);await load(session.role,filter.q,filter.status);window.alert('Project saved.');}catch(error){window.alert(error.message);}};
 const remove=async(kind,item)=>{if(!window.confirm(`Delete ${item.name}? This cannot be undone.`))return;try{await api(`/api/${kind}/${item.id}`,{method:'DELETE'});if(selected?.id===item.id)setSelected(null);await load(session.role,filter.q,filter.status);window.alert(`${kind==='clients'?'Client':'Project'} deleted.`);}catch(error){window.alert(error.message);}};
 const updateProgress=async(project,changes)=>{const safeChanges=changes.progress===undefined?changes:{...changes,progress:boundedProgress(changes.progress)};try{const payload=await api(`/api/projects/${project.id}`,request('PATCH',safeChanges));setProjects(current=>current.map(item=>item.id===project.id?payload.project:item));setSelected(current=>current?.id===project.id?payload.project:current);window.alert('Project progress updated.');}catch(error){await load(session.role,filter.q,filter.status);window.alert(error.message);}};
 const editProject=item=>{setEditingProject(item.id);setProjectForm({name:item.name,description:item.description,status:item.status,progress:item.progress,clientId:item.clientId,memberIds:item.members.map(member=>member.id)});window.scrollTo({top:0,behavior:'smooth'});};
 const stats={total:projects.length,active:projects.filter(item=>item.status==='in-progress').length,completed:projects.filter(item=>item.status==='completed').length};
 if(session.loading)return <main className="project-shell"><p role="status">Checking project access...</p></main>;
 if(!session.role)return <main className="project-shell"><section className="project-access"><Logo/><h1>Project access unavailable</h1><p>{session.error}</p><a className="button" href={session.status===401?'/login?returnTo=%2Fprojects':'/dashboard'}>{session.status===401?'Sign in':'Return to dashboard'}</a></section></main>;
 return <main className="project-shell"><div className="project-page"><header className="project-header"><div><Logo href={root?'/admin':'/dashboard'}/><h1>{root?'Client & project management':'My assigned projects'}</h1><p>{root?'Manage clients, delivery and team assignments.':'Update progress for projects assigned to you.'}</p></div><a className="button button-ghost" href={root?'/admin':'/dashboard'}>Back</a></header><section className="project-stats"><div><strong>{stats.total}</strong><span>Total</span></div><div><strong>{stats.active}</strong><span>Active</span></div><div><strong>{stats.completed}</strong><span>Completed</span></div></section>
 {root&&<div className="project-editors"><section className="admin-panel client-editor"><h2>{editingClient?'Edit client':'New client'}</h2><form className="project-form" onSubmit={saveClient}><label>Name<input required maxLength="120" value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})}/></label><label>Email<input required type="email" maxLength="254" value={clientForm.email} onChange={e=>setClientForm({...clientForm,email:e.target.value})}/></label><label>Phone<input maxLength="40" value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})}/></label><div className="project-actions client-actions">{editingClient&&<button type="button" className="button button-ghost" onClick={()=>{setEditingClient(null);setClientForm(emptyClient);}}>Cancel</button>}<button className="button"><HiOutlinePlus/> Save client</button></div></form></section><section className="admin-panel"><h2>{editingProject?'Edit project':'New project'}</h2><form className="project-form" onSubmit={saveProject}><label>Name<input required maxLength="120" value={projectForm.name} onChange={e=>setProjectForm({...projectForm,name:e.target.value})}/></label><label>Client<select required value={projectForm.clientId} onChange={e=>setProjectForm({...projectForm,clientId:e.target.value})}><option value="">Select client</option>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>Status<select value={projectForm.status} onChange={e=>{const status=e.target.value;setProjectForm({...projectForm,status,progress:statusProgress(status,projectForm.progress)});}}>{STATUSES.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" disabled={projectForm.status!=='in-progress'} value={projectForm.progress} onChange={e=>setProjectForm({...projectForm,progress:e.target.value})}/></label><label className="full">Description<textarea rows="4" maxLength="3000" value={projectForm.description} onChange={e=>setProjectForm({...projectForm,description:e.target.value})}/></label><fieldset className="full member-picker"><legend>Team members</legend>{staff.length?staff.map(member=><label key={member.id}><input type="checkbox" checked={projectForm.memberIds.includes(member.id)} onChange={e=>setProjectForm({...projectForm,memberIds:e.target.checked?[...projectForm.memberIds,member.id]:projectForm.memberIds.filter(id=>id!==member.id)})}/><span>{member.name}<small>{member.email}</small></span></label>):<p>No staff accounts are available.</p>}</fieldset><div className="project-actions full">{editingProject&&<button type="button" className="button button-ghost" onClick={()=>{setEditingProject(null);setProjectForm(emptyProject);}}>Cancel</button>}<button className="button"><HiOutlinePlus/> Save project</button></div></form></section></div>}
 {root&&<section className="admin-panel"><h2>Clients</h2><div className="admin-list">{clients.map(client=><article key={client.id}><div><h3>{client.name}</h3><p>{client.email}{client.phone&&` · ${client.phone}`}</p><small>{client.projectCount} project(s)</small></div><div><button className="button button-ghost button-small" onClick={()=>{setEditingClient(client.id);setClientForm({name:client.name,email:client.email,phone:client.phone});}}><HiOutlinePencilSquare/> Edit</button><button className="button button-danger button-small" onClick={()=>remove('clients',client)}><HiOutlineTrash/> Delete</button></div></article>)}</div></section>}
 <section className="admin-panel"><div className="project-list-heading"><h2>Projects</h2><form onSubmit={e=>{e.preventDefault();load(session.role,filter.q,filter.status);}}><input aria-label="Search projects" placeholder="Search project or client" value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})}/><select aria-label="Filter project status" value={filter.status} onChange={e=>{const next={...filter,status:e.target.value};setFilter(next);load(session.role,next.q,next.status);}}><option value="">All statuses</option>{STATUSES.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select><button className="button button-small">Search</button></form></div>{!projects.length&&<p>No projects are available.</p>}<div className="project-grid">{projects.map(project=><article className="project-card" key={project.id}><button className="project-card-main" onClick={()=>setSelected(project)}><span className={`project-status status-${project.status}`}>{label(project.status)}</span><h3>{project.name}</h3><p>{project.clientName}</p><div className="progress-track"><span style={{width:`${project.progress}%`}}/></div><small>{project.progress}% · {project.members.map(member=>member.name).join(', ')||'Unassigned'}</small></button>{root?<div className="project-card-actions"><button onClick={()=>editProject(project)}><HiOutlinePencilSquare/> Edit</button><button onClick={()=>remove('projects',project)}><HiOutlineTrash/> Delete</button></div>:<div className="staff-progress"><label>Status<select value={project.status} onChange={e=>updateProgress(project,{status:e.target.value})}>{STATUSES.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label><label>Progress<input type="number" min="0" max="100" disabled={project.status!=='in-progress'} value={project.progress} onBlur={e=>updateProgress(project,{progress:Number(e.target.value)})} onChange={e=>setProjects(current=>current.map(item=>item.id===project.id?{...item,progress:Number(e.target.value)}:item))}/></label></div>}</article>)}</div></section>
 {selected&&<section className="admin-panel project-detail"><div><span className={`project-status status-${selected.status}`}>{label(selected.status)}</span><h2>{selected.name}</h2><p>{selected.description||'No description provided.'}</p></div><dl><div><dt>Client</dt><dd>{selected.clientName}</dd></div><div><dt>Progress</dt><dd>{selected.progress}%</dd></div><div><dt>Team</dt><dd>{selected.members.map(member=>member.name).join(', ')||'Unassigned'}</dd></div><div><dt>Updated</dt><dd>{new Date(selected.updatedAt).toLocaleString()}</dd></div></dl></section>}</div></main>;
}
